### ISSUE TITLE
results of the camera calibration

### ISSUE THREAD

**Issue by azishabibi** [NikolasEnt/soccernet-calibration-sportlight#7]
Hi,
Thanks for the open source code. I would like to ask in this link https://nikolasent.github.io/deeplearning/computervision/2023/06/20/SoccerNet-Camera-Calibration-2023.htmlhttps://nikolasent.github.io/deeplearning/computervision/2023/06/20/SoccerNet-Camera-Calibration-2023.html, how is Fig 8 generated? I cannot find the code for that in the repo. 
Thanks.

**Comment by NikolasEnt** [comment]
Hi, thank you for your interest in the project.
I cannot remember exactly because it was used for the figures only.
I believe we used the code for drawing predictions from the official baseline: https://github.com/NikolasEnt/soccernet-calibration-sportlight/blob/134662d5ab8a05be2d9d64a128c8d7bd07fc8189/baseline/camera.py#L315

**Comment by azishabibi** [comment]
Thanks!
